-- Seed of the legacy "Honzíkova moudra" collection (128 quotes exported from the old MySQL/phpMyAdmin site).
-- Imported as 'approved' because they are the owner's real published collection (ACTIVE=1 in the export).
-- Idempotent by legacy_id; sends NO notifications (no publication_batches / notification_outbox rows are created).
-- Images are NOT set here: the original image files were not provided yet. The 17 legacy filenames are recorded
-- in docs/legacy-image-map.json for a later, separate image upload + hm_attach_quote_image step.
insert into public.hm_quotes (legacy_id, text, status, first_published_at, created_at) values
  ('1', 'Víc je víc než míň', 'approved', '2023-12-27'::date::timestamp at time zone 'Europe/Prague', '2023-12-27'::date::timestamp at time zone 'Europe/Prague'),
  ('2', 'Smrt je vysvobození.', 'approved', '2023-12-27'::date::timestamp at time zone 'Europe/Prague', '2023-12-27'::date::timestamp at time zone 'Europe/Prague'),
  ('3', 'Kde je cesta, tam je vůle.', 'approved', '2023-12-27'::date::timestamp at time zone 'Europe/Prague', '2023-12-27'::date::timestamp at time zone 'Europe/Prague'),
  ('4', 'Nakonec vždy všechno dobře dopadne.', 'approved', '2023-12-27'::date::timestamp at time zone 'Europe/Prague', '2023-12-27'::date::timestamp at time zone 'Europe/Prague'),
  ('5', 'Nikdy nikomu nevěř.', 'approved', '2023-12-27'::date::timestamp at time zone 'Europe/Prague', '2023-12-27'::date::timestamp at time zone 'Europe/Prague'),
  ('6', 'Brbli brbli ...', 'approved', '2023-12-27'::date::timestamp at time zone 'Europe/Prague', '2023-12-27'::date::timestamp at time zone 'Europe/Prague'),
  ('7', 'Byl to můj nápad, takže musel bejt dobrej.', 'approved', '2023-12-27'::date::timestamp at time zone 'Europe/Prague', '2023-12-27'::date::timestamp at time zone 'Europe/Prague'),
  ('8', 'Spánek je jen levná náhražka kofeinu.', 'approved', '2023-12-27'::date::timestamp at time zone 'Europe/Prague', '2023-12-27'::date::timestamp at time zone 'Europe/Prague'),
  ('9', 'Třetí pivo probouzí.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('10', 'Nikdy ničeho nelituj.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('11', 'Nevědomost je sladká.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('12', 'Raz si dole, raz si dole.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('13', 'Najprv práca, potom práca.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('14', 'I špatná cesta je dobrá cesta, když je dobrý cíl.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('15', 'Když starého psa novým kouskům nenaučíte, pořiďte si psa nového.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('16', 'I život dokáže být jednodušší, když se člověk trochu snaží.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('17', 'Všechno má svoji budoucnost.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('18', 'Neboj se, bude hůř.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('19', 'Vim co hledám, ale říct ti to nemůžu.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('20', 'Flákej se co nejvíc.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('21', 'Every triangle is love triangle, when you love triangles', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('22', 'Z vítězů se poražení nestávají', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('23', 'Každý názor má svou pravdu.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('24', 'Když ztrácíš čas, není času nazbyt.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('25', 'Více žití, rozum v řiti.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('26', 'Pamatuji si jméno každého, koho jsem kdy poznal, jelikož nevím o nikom, na koho bych zapomněl.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('27', 'S nízkými cíly lze dosáhnout velké radosti', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('28', 'Člověk musí žít, aby živen mohl být.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('29', 'Čím více uživatelů založím, tím víc hvězdiček budu mít.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('30', 'To je tím, že je doma, ztloustnul a hůř se mu pak dýchá ...covid je jen příčina, proč byl doma.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('31', 'Být v Las Vegas a nehodit si aspoň ruletu, je jako bejt někde a neudělat něco.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('32', 'I noc je ráno.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('33', 'Alkoholismus je jen pro chytrý.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('34', 'Nechval dne před štědrým večerem.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('35', 'Pivo v hospodě dělá hodně.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('36', 'Člověk neví co chce, dokud nezjistí co může mít.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('37', 'Chlastáme tu, protože tu jsme.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('38', 'Na všechno máš tolik času, kolik ho máš.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('39', 'Zítra bude hůř, dnes je dnes.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('40', 'Kdo nehraje, nevyhraje.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('41', 'Komu pivo, tomu pivo.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('42', 'Čím víc na to myslím, tím spíš je to dál.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('43', 'Když si myslíš, že jsi opilý, jsi opilý.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('44', 'Komu smrdí alkohol, tomu smrdí práce.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('45', 'Přátelé jsou rodina, kterou si sami vybíráte.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('46', 'Když na nás nesvítí, tak nevidíme déšť.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('47', 'Jistá nejistota.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('48', 'S rostoucí hladinou alkoholu roste míra porozumění.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('49', 'Všichni jsou jen kurvy převlečený za kamarády.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('50', 'Jestli se chceš poučit ze svých chyb, nedělej chyby další.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('51', 'My chudáci, co umíme všechno, musíme zvládat všechno.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('52', 'Buď šťastný/á za to jaký jsi. ...až na to přijdeš.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('53', 'I myčka má své dny.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('54', 'Má moudra jsou možná pro všechny, ale rozhodně nejsou pro každého.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('55', 'Je mnoho mnoho hodin, a tak málo spánku.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('56', 'Není věnec, není jägger.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('57', 'Ostří víc tupí.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('58', 'Kdo moc vidí, moc se dozví.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('59', 'Slunce vychází za tmy.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('60', 'Kdo běží, ten běží. Kdo sedí, ten sedí. Kdo leží, ten leží. Ale všichni pijou! -- Rock Castle 2023 --', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('61', 'Kto zaváha nežere.... a preto sa ožere.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('62', 'Když nic není, tak nic nebude..', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('63', 'Kdo moc cinká, málo spinká. --- Otevřené sklepy 2023 ---', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('64', 'Co je a nebude, nebude když bude.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('65', 'Tvůj osud je sice předurčen, ale závisí na tvý volbě.', 'approved', '2023-12-28'::date::timestamp at time zone 'Europe/Prague', '2023-12-28'::date::timestamp at time zone 'Europe/Prague'),
  ('66', 'Než někam pojedeš, tak si ukliď', 'approved', '2024-01-13'::date::timestamp at time zone 'Europe/Prague', '2024-01-13'::date::timestamp at time zone 'Europe/Prague'),
  ('67', 'Vzhledem k tomu, že k nám nikdo nechodí, jsme všechno snědli sami', 'approved', '2024-01-13'::date::timestamp at time zone 'Europe/Prague', '2024-01-13'::date::timestamp at time zone 'Europe/Prague'),
  ('68', 'Když je prdel v životě, není život v prdeli', 'approved', '2024-01-14'::date::timestamp at time zone 'Europe/Prague', '2024-01-14'::date::timestamp at time zone 'Europe/Prague'),
  ('69', 'Když má problém řešení, vyřeší se sám. Když ne, starosti nepomohou.', 'approved', '2024-01-14'::date::timestamp at time zone 'Europe/Prague', '2024-01-14'::date::timestamp at time zone 'Europe/Prague'),
  ('70', 'Dobrý stres nemůže být zlý.', 'approved', '2024-01-15'::date::timestamp at time zone 'Europe/Prague', '2024-01-15'::date::timestamp at time zone 'Europe/Prague'),
  ('71', 'Společné neštěstí tvoří společný úspěch.', 'approved', '2024-01-17'::date::timestamp at time zone 'Europe/Prague', '2024-01-17'::date::timestamp at time zone 'Europe/Prague'),
  ('72', 'Kdo nechlastá, ten nebleje', 'approved', '2024-01-17'::date::timestamp at time zone 'Europe/Prague', '2024-01-17'::date::timestamp at time zone 'Europe/Prague'),
  ('73', 'Stačí jenom vyhrát.', 'approved', '2024-03-11'::date::timestamp at time zone 'Europe/Prague', '2024-03-11'::date::timestamp at time zone 'Europe/Prague'),
  ('74', 'Kdo chce bycha honit, ručku vždycky najde', 'approved', '2024-03-12'::date::timestamp at time zone 'Europe/Prague', '2024-03-12'::date::timestamp at time zone 'Europe/Prague'),
  ('75', 'Rozdíl mezi skillem a náhodou je v nedůvěře.', 'approved', '2024-03-12'::date::timestamp at time zone 'Europe/Prague', '2024-03-12'::date::timestamp at time zone 'Europe/Prague'),
  ('76', 'Práce je jen legrace dělaná pro zábavu.', 'approved', '2024-03-15'::date::timestamp at time zone 'Europe/Prague', '2024-03-15'::date::timestamp at time zone 'Europe/Prague'),
  ('77', 'Všechno je jen otázka mysli a já jsem úplně vymyšlenej.', 'approved', '2024-03-15'::date::timestamp at time zone 'Europe/Prague', '2024-03-15'::date::timestamp at time zone 'Europe/Prague'),
  ('78', 'Přiznat si existenciální krizi je snadný, ale naučit se s ní žít, to je umění.', 'approved', '2024-03-15'::date::timestamp at time zone 'Europe/Prague', '2024-03-15'::date::timestamp at time zone 'Europe/Prague'),
  ('79', 'Včerejší zmrzlina tě neochladí.', 'approved', '2024-03-15'::date::timestamp at time zone 'Europe/Prague', '2024-03-15'::date::timestamp at time zone 'Europe/Prague'),
  ('80', 'Stáří lze poznat tak, že na akci tě zajímá spíš jídlo, než alkohol', 'approved', '2024-03-15'::date::timestamp at time zone 'Europe/Prague', '2024-03-15'::date::timestamp at time zone 'Europe/Prague'),
  ('81', 'Teprve tehdy, kdy je člověk milován může konečně začít jíst...a vesele jíst.', 'approved', '2024-03-15'::date::timestamp at time zone 'Europe/Prague', '2024-03-15'::date::timestamp at time zone 'Europe/Prague'),
  ('82', 'Není důležitý cíl, jako výsledek', 'approved', '2024-03-15'::date::timestamp at time zone 'Europe/Prague', '2024-03-15'::date::timestamp at time zone 'Europe/Prague'),
  ('83', 'Grilování je pro well-doneisty', 'approved', '2024-03-15'::date::timestamp at time zone 'Europe/Prague', '2024-03-15'::date::timestamp at time zone 'Europe/Prague'),
  ('84', 'Bobr nepije teplý pivo', 'approved', '2024-03-15'::date::timestamp at time zone 'Europe/Prague', '2024-03-15'::date::timestamp at time zone 'Europe/Prague'),
  ('85', 'Midgard je po cestě... Midgard je vždycky po cestě.... Když seš na cestě do Midgardu', 'approved', '2024-03-15'::date::timestamp at time zone 'Europe/Prague', '2024-03-15'::date::timestamp at time zone 'Europe/Prague'),
  ('86', 'Beru všechno, vyhodit si to můžu sám', 'approved', '2024-03-27'::date::timestamp at time zone 'Europe/Prague', '2024-03-27'::date::timestamp at time zone 'Europe/Prague'),
  ('87', 'Doma je tam, kde sereš rád.', 'approved', '2024-04-12'::date::timestamp at time zone 'Europe/Prague', '2024-04-12'::date::timestamp at time zone 'Europe/Prague'),
  ('88', 'Každý hrdina, ve svý linii.', 'approved', '2024-04-12'::date::timestamp at time zone 'Europe/Prague', '2024-04-12'::date::timestamp at time zone 'Europe/Prague'),
  ('89', 'Když můžeš tak musíš.', 'approved', '2024-04-12'::date::timestamp at time zone 'Europe/Prague', '2024-04-12'::date::timestamp at time zone 'Europe/Prague'),
  ('90', 'Vždyť z té láhve vůbec neubývá, co na tom, že je druhá...', 'approved', '2024-04-18'::date::timestamp at time zone 'Europe/Prague', '2024-04-18'::date::timestamp at time zone 'Europe/Prague'),
  ('91', 'Netrpíš když nejseš.', 'approved', '2024-04-23'::date::timestamp at time zone 'Europe/Prague', '2024-04-23'::date::timestamp at time zone 'Europe/Prague'),
  ('92', 'Jak se pozná hloupý člověk ve skupině? Cítí se stejně normálně jako ti ostatní.', 'approved', '2024-05-03'::date::timestamp at time zone 'Europe/Prague', '2024-05-03'::date::timestamp at time zone 'Europe/Prague'),
  ('93', 'Vážím si každého okamžiku, protože cokoliv co udělám, je hrozně náročný.', 'approved', '2024-05-28'::date::timestamp at time zone 'Europe/Prague', '2024-05-28'::date::timestamp at time zone 'Europe/Prague'),
  ('94', 'Kdo nic nemá, nic neutratí', 'approved', '2024-05-30'::date::timestamp at time zone 'Europe/Prague', '2024-05-30'::date::timestamp at time zone 'Europe/Prague'),
  ('95', 'Není dort jako torta.', 'approved', '2024-06-28'::date::timestamp at time zone 'Europe/Prague', '2024-06-28'::date::timestamp at time zone 'Europe/Prague'),
  ('96', 'Je mensi sance ze te trefi blesk kdyz mas v ruce destnik, nez kdyz mas prazdny pullitr!', 'approved', '2025-11-12'::date::timestamp at time zone 'Europe/Prague', '2025-11-12'::date::timestamp at time zone 'Europe/Prague'),
  ('97', 'Na alkohol nesmíš pít.', 'approved', '2025-11-12'::date::timestamp at time zone 'Europe/Prague', '2025-11-12'::date::timestamp at time zone 'Europe/Prague'),
  ('98', 'Ve výsledku jde o výsledek', 'approved', '2025-11-12'::date::timestamp at time zone 'Europe/Prague', '2025-11-12'::date::timestamp at time zone 'Europe/Prague'),
  ('99', 'Život je jen zkratka ke smrti.', 'approved', '2025-11-12'::date::timestamp at time zone 'Europe/Prague', '2025-11-12'::date::timestamp at time zone 'Europe/Prague'),
  ('100', 'Mám bohužel malé pívo, jelikož nejsou velké skleničky.', 'approved', '2025-11-12'::date::timestamp at time zone 'Europe/Prague', '2025-11-12'::date::timestamp at time zone 'Europe/Prague'),
  ('101', 'Není důležitá cesta, ale výsledek.', 'approved', '2025-11-12'::date::timestamp at time zone 'Europe/Prague', '2025-11-12'::date::timestamp at time zone 'Europe/Prague'),
  ('102', 'Chytrý ten, kdo kolem něho hloupý je.', 'approved', '2025-11-12'::date::timestamp at time zone 'Europe/Prague', '2025-11-12'::date::timestamp at time zone 'Europe/Prague'),
  ('103', 'Je to tak jak to je a jseš kde jseš.', 'approved', '2025-11-12'::date::timestamp at time zone 'Europe/Prague', '2025-11-12'::date::timestamp at time zone 'Europe/Prague'),
  ('104', 'Když se člověk snaží být hodný, není to vlastně fér', 'approved', '2025-11-12'::date::timestamp at time zone 'Europe/Prague', '2025-11-12'::date::timestamp at time zone 'Europe/Prague'),
  ('105', 'Když si splníš své sny, nemáš pak o čem snít.', 'approved', '2025-11-12'::date::timestamp at time zone 'Europe/Prague', '2025-11-12'::date::timestamp at time zone 'Europe/Prague'),
  ('106', 'Čím míň to nutíš, tím víc to přijde samo', 'approved', '2025-11-12'::date::timestamp at time zone 'Europe/Prague', '2025-11-12'::date::timestamp at time zone 'Europe/Prague'),
  ('107', 'Piuko...to je když máš k pivu vřelý vztah!!', 'approved', '2025-11-13'::date::timestamp at time zone 'Europe/Prague', '2025-11-13'::date::timestamp at time zone 'Europe/Prague'),
  ('108', 'Přátelství tvoří nepřátele', 'approved', '2025-11-13'::date::timestamp at time zone 'Europe/Prague', '2025-11-13'::date::timestamp at time zone 'Europe/Prague'),
  ('109', 'Pokud máte nápad, uskutečněte ho!!', 'approved', '2025-11-13'::date::timestamp at time zone 'Europe/Prague', '2025-11-13'::date::timestamp at time zone 'Europe/Prague'),
  ('110', 'Život je reality show', 'approved', '2025-11-13'::date::timestamp at time zone 'Europe/Prague', '2025-11-13'::date::timestamp at time zone 'Europe/Prague'),
  ('111', 'Jedno je líp než ne..', 'approved', '2025-11-13'::date::timestamp at time zone 'Europe/Prague', '2025-11-13'::date::timestamp at time zone 'Europe/Prague'),
  ('112', 'Každá holka by měla mít svýho Honzíka.', 'approved', '2025-11-13'::date::timestamp at time zone 'Europe/Prague', '2025-11-13'::date::timestamp at time zone 'Europe/Prague'),
  ('113', 'Ve skutečnosti nejsi alkáč, ale zaklínač!
-- Honzík na cestě do Brna --', 'approved', '2025-11-13'::date::timestamp at time zone 'Europe/Prague', '2025-11-13'::date::timestamp at time zone 'Europe/Prague'),
  ('114', 'Lituju hodně věcí, ale ne že jsem poznala Honzíka.', 'approved', '2025-11-13'::date::timestamp at time zone 'Europe/Prague', '2025-11-13'::date::timestamp at time zone 'Europe/Prague'),
  ('115', 'Ještě nevím co to je, ale už jsem to vyrobil', 'approved', '2025-11-13'::date::timestamp at time zone 'Europe/Prague', '2025-11-13'::date::timestamp at time zone 'Europe/Prague'),
  ('116', 'Je čas jít dál a musíte si to zažít..', 'approved', '2025-11-13'::date::timestamp at time zone 'Europe/Prague', '2025-11-13'::date::timestamp at time zone 'Europe/Prague'),
  ('117', 'Totem je kotva a kotva je totem..', 'approved', '2025-11-13'::date::timestamp at time zone 'Europe/Prague', '2025-11-13'::date::timestamp at time zone 'Europe/Prague'),
  ('118', 'Je mi jedno jak se jmenuje, hlavně že vím na koho mluvím', 'approved', '2025-11-13'::date::timestamp at time zone 'Europe/Prague', '2025-11-13'::date::timestamp at time zone 'Europe/Prague'),
  ('119', 'Drby jsou základem společnosti', 'approved', '2025-11-13'::date::timestamp at time zone 'Europe/Prague', '2025-11-13'::date::timestamp at time zone 'Europe/Prague'),
  ('120', 'Po druhé lahvi je každý generál
- Honzík 23.10.2025 -', 'approved', '2025-11-13'::date::timestamp at time zone 'Europe/Prague', '2025-11-13'::date::timestamp at time zone 'Europe/Prague'),
  ('121', 'Nechceme vědět informace, které bychom vědět nechtěli', 'approved', '2025-11-13'::date::timestamp at time zone 'Europe/Prague', '2025-11-13'::date::timestamp at time zone 'Europe/Prague'),
  ('122', 'Není krásy bez vrásek', 'approved', '2025-11-13'::date::timestamp at time zone 'Europe/Prague', '2025-11-13'::date::timestamp at time zone 'Europe/Prague'),
  ('123', 'Udělám čáru, někdo musí bejt leader', 'approved', '2025-11-13'::date::timestamp at time zone 'Europe/Prague', '2025-11-13'::date::timestamp at time zone 'Europe/Prague'),
  ('124', 'Každý život bude režie', 'approved', '2025-11-13'::date::timestamp at time zone 'Europe/Prague', '2025-11-13'::date::timestamp at time zone 'Europe/Prague'),
  ('125', 'Bylo to hezký, ale není to moje vina', 'approved', '2025-11-13'::date::timestamp at time zone 'Europe/Prague', '2025-11-13'::date::timestamp at time zone 'Europe/Prague'),
  ('126', 'Nesmysl se stal realitou', 'approved', '2025-11-13'::date::timestamp at time zone 'Europe/Prague', '2025-11-13'::date::timestamp at time zone 'Europe/Prague'),
  ('127', 'Nemusíš věřit v Boha abys platil desátek', 'approved', '2025-11-13'::date::timestamp at time zone 'Europe/Prague', '2025-11-13'::date::timestamp at time zone 'Europe/Prague'),
  ('128', 'Porozumění je převlečená lítost', 'approved', '2025-11-13'::date::timestamp at time zone 'Europe/Prague', '2025-11-13'::date::timestamp at time zone 'Europe/Prague')
on conflict (legacy_id) do nothing;
